### ISSUE TITLE
Prevent scrolling below the scrollview buffer area

### ISSUE THREAD

**Issue by SkwalExe** [joshka/tui-widgets#35]
I find it very annoying that when the scrollview buffer doesn't within the render area, and that the scrollbar is displayed, it is possible to scroll below the buffer, like in the capture below:

![image](https://github.com/user-attachments/assets/d880c008-6e8b-4e03-a210-c2ccfd2d235b)

I think it would be better to hide the empty area by default, or at least, add an option to do so. It would therefore not be possible to scroll below the end of the area, like in this screenshot:

![image](https://github.com/user-attachments/assets/4f695c24-5a12-4e19-9379-c3bda5505fa8)

I already implemented this change in a fork that I am using for my projects, I also modified the scrollbar behavior accordingly. Would a PR be accepted?

**Comment by joshka** [comment]
It sure would be. Check https://github.com/joshka/tui-widgets/issues/8 / https://github.com/joshka/tui-scrollview/pull/29 for some previous work on this - take note of how it's tested. It would be good to see how close your implementation to this was.

One thing I do think is worth doing here is making this a config option. What do you think about that? Likely an enum representing the possible approaches. I'm not sure what the right name for these would be. Maybe scroll_limit, or end_of_area_behavior. (I don't really like either of those, but there's likely a idea in the middle).

**Comment by SkwalExe** [comment]
I don't really see why one would want to choose the current behavior, as it doesn't really make sense to scroll beyond the defined area. It would also make the implementation easier, choosing a name for the parameter probably being the most difficult part :laughing: 

I'm going to take a look at the PR you mentioned when I have time

**Comment by joshka** [comment]
Definitely the proposed idea (limiting scrolling beyond the last full page) should be the default. But to get an idea of why this might be useful, take a look at any text editor and you'll often see the scrolling approach that is seen here. You might use this when lining up certain things with other things in other simultaneously scrolled / moved things

That said, now I think about it a bit more, one way to get the current behavior is to add the extra space to the scrollview buffer, and just not write anything to it. So I'd be fine with making the limited view the only thing that works rather than this being a setting.

**Comment by SkwalExe** [comment]
I took a look at [#29](https://github.com/joshka/tui-scrollview/pull/29) and it only implements this change on the vertical scrolling, do we also want the same behavior on the horizontal scrolling? As far as I'm concerned, it should also be the default.

**Comment by louis-thevenet** [comment]
> I took a look at [#29](https://github.com/joshka/tui-scrollview/pull/29) and it only implements this change on the vertical scrolling, do we also want the same behavior on the horizontal scrolling? As far as I'm concerned, it should also be the default.

Just spent quite some time thinking this was a bug in my code... I also think it should be the default. For horizontal scrolling too, for consistency and also because vertical scrolling is probably more frequent, vertical and horizontal scrollbars should be independent. 

Are you working on the issue ?

**Comment by joshka** [comment]
I'm not working on it. Feel free to jump in and get it done. This should be for both horizontal and vertical. We don't need configuration on this - it should be the default way this works. Anyone that needs the previous behavior can add space to their buffer in accordance to the amount of overscroll they need.
